version: '3.3'

services:
  get-version:
    build:
      context: .
      dockerfile: Version.Dockerfile
      
  factorio:
    build:
      context: .
      args:
        FACTORIO_VERSION: ${FACTORIO_VERSION}